'use strict';

// account action constants
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_REQUEST = 'FETCHING_TRANSACTIONS';
export const API_FAIL = 'API_FAIL';
export const AFFIX_QUERY = 'AFFIX_QUERY';
export const SHOULD_FETCH_ALL = 'SHOULD_FETCH_ALL';
