'use strict';

// Budget action constants
export const CREATE_BUDGET = 'CREATE_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';
export const GET_BUDGET = 'GET_BUDGET';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const FETCH_BUDGETS_SUCCESS = 'FETCH_BUDGETS_SUCCESS';
export const FETCH_BUDGETS_REQUEST = 'FETCHING_BUDGETS';
export const CREATE_BUDGET_SUCCESS = 'CREATE_BUDGET_SUCCESS';
export const DELETE_BUDGET_SUCCESS = 'DELETE_BUDGET_SUCCESS';
export const UPDATE_BUDGET_SUCCESS = 'UPDATE_BUDGET_SUCCESS';
export const API_FAIL = 'API_FAIL';
