'use strict';

export const CREATE_MERCHANT = 'CREATE_MERCHANT';
export const DELETE_MERCHANT = 'DELETE_MERCHANT';
export const GET_MERCHANT = 'GET_MERCHANT';
export const UPDATE_MERCHANT = 'UPDATE_MERCHANT';
export const FETCH_MERCHANTS_SUCCESS = 'FETCH_MERCHANTS_SUCCESS';
export const FETCH_MERCHANTS_REQUEST = 'FETCHING_MERCHANTS';
export const CREATE_MERCHANT_SUCCESS = 'CREATE_MERCHANT_SUCCESS';
export const DELETE_MERCHANT_SUCCESS = 'DELETE_MERCHANT_SUCCESS';
export const UPDATE_MERCHANT_SUCCESS = 'UPDATE_MERCHANT_SUCCESS';
export const API_FAIL = 'API_FAIL';