'use strict';

// Transaction action constants
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const GET_TRANSACTION = 'GET_TRANSACTION';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_REQUEST = 'FETCHING_TRANSACTIONS';
export const FETCH_TRANSACTIONS_FAIL = 'FETCH_TRANSACTIONS_FAILURE';