'use strict';

// Transaction action constants
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const GET_TRANSACTION = 'GET_TRANSACTION';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_REQUEST = 'FETCHING_TRANSACTIONS';
export const API_FAIL = 'API_FAIL';
export const AFFIX_QUERY = 'AFFIX_QUERY';
